enum Errorcode
{
    FILE_NOT_FOUND_ERROR,
    REFERENCE_ERROR,
    RUNTIME_ERROR,
    LEXICAL_ERROR,
    SYNTAX_ERROR,
    EXPECTED_EXPR,
    OUT_OF_RANGE,
    ARITHMETIC_ERROR,
    EXPECTED_LIT,
    EXPECTED_STR
};